### ISSUE TITLE
Duplicate entries when a product is new

### ISSUE THREAD

**Issue by Mariocoleguilla** [bobbypine/SupremeManualBot#2]
Hi bobbypine,

I've been reading the code and I noticed something: The process opens two tabs when a product is new due to the new product being on the "new" category and also in his own category.

I could implement a way to execute the process with a .yaml file for configuration that could enable the user to imput whether he wants a new product or not, so the process doesn't open 2 tabs. The .yaml config file could be used also to imput various numbers of items with more than one key-to-match, so it matches every key. With a .yaml file, the process wouldn't need to get a keyboard input and the process could be executed only with a fixed command. What do you think?

Greetings.

**Comment by bobbypine** [comment]
This isn't due to the 'new' category. The program, by design, doesn't search in the new category because the online release of week one doesn't have a new category, which would render the program useless that week. So in order to avoid this it searches every category _**except**_ for new. The duplicate tabs is a known issue, and happens from time to time, but not every week. I don't have an answer for why it happens, but your initial hunch isn't correct.
